file_format: "1"
id: gameroy_advanced
name: gameroy_advanced
type: shield
url: https://keystonecaps.store/?product=game-roy-advance-game-pad-group-buy-preorder
requires: [pro_micro]
features:
  - keys
  - encoder
siblings:
  - gameroy_advanced_left
  - gameroy_advanced_right